name: surgabuku
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  get_cli: ^1.8.4
  google_fonts: ^4.0.4
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  font_awesome_flutter: ^10.7.0
  device_info_plus: ^9.1.2
  get: 4.6.6
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  flutter: 
    sdk: flutter
  form_validator: ^2.1.1
  flutter_dash: 1.0.0
  iconsax: ^0.0.8
  fluttertoast: ^8.2.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

